'use client';

import type { ReactNode } from 'react';
import { useMemo, useState } from 'react';
import { AlertTriangle, BarChart3, BookOpen, Bot, CheckCircle2, MessageSquare, Plus, Save, Search, Sparkles, Workflow, X, UserCheck } from 'lucide-react';
import { MotionDiv, fadeUp } from '@/components/motion';
import demo from '@/data/demo.json';

type View = 'overview' | 'knowledge' | 'conversations' | 'workflow';
type KnowledgeItem = { id: number; title: string; category: string; status: string; updated: string };
type Conversation = (typeof demo.conversations)[number] & { handled?: boolean; note?: string; aiReply?: string };

const replyTemplates = [
  '模型识别到该问题属于账单/订阅类意图，建议先返回可自助操作路径；若涉及合同金额或发票主体变更，则进入人工复核。',
  '当前会话与知识库中的账户管理条目相似度较高，可以直接给出步骤式回复，并在末尾提供人工入口。',
  '该请求存在低置信度风险，建议 AI 只回答已验证部分，并将不确定信息交由人工坐席确认。',
];

export function DemoConsole() {
  const [view, setView] = useState<View>('overview');
  const [range, setRange] = useState<'7d' | '30d'>('7d');
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState('全部');
  const [items, setItems] = useState<KnowledgeItem[]>(demo.knowledge);
  const [conversations, setConversations] = useState<Conversation[]>(demo.conversations);
  const [selected, setSelected] = useState<Conversation | null>(null);
  const [toast, setToast] = useState('');
  const [tab, setTab] = useState('意图识别');
  const [loading, setLoading] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [threshold, setThreshold] = useState(70);
  const metrics = demo.metrics[range];

  const nav = [['overview', '概览', BarChart3], ['knowledge', '知识库', BookOpen], ['conversations', '会话识别', MessageSquare], ['workflow', '模型策略', Workflow]] as const;
  const filteredConversations = useMemo(() => conversations.filter((item) => (status === '全部' || item.status === status) && `${item.customer}${item.topic}${item.channel}`.includes(query)), [conversations, status, query]);

  function notify(message: string) { setToast(message); setTimeout(() => setToast(''), 2500); }
  function switchTab(nextTab: string) { setTab(nextTab); setLoading(true); setTimeout(() => setLoading(false), 450); }
  function markHandled(id: string) { setConversations((prev) => prev.map((item) => item.id === id ? { ...item, status: '已解决', handled: true, note: '已由人工确认处理' } : item)); setSelected((prev) => prev && prev.id === id ? { ...prev, status: '已解决', handled: true, note: '已由人工确认处理' } : prev); notify('会话已标记为人工处理完成'); }
  function generateReply(item: Conversation) {
    setGenerating(true);
    setTimeout(() => {
      const reply = replyTemplates[Math.abs(item.confidence + item.id.length) % replyTemplates.length];
      setConversations((prev) => prev.map((conv) => conv.id === item.id ? { ...conv, aiReply: reply } : conv));
      setSelected((prev) => prev && prev.id === item.id ? { ...prev, aiReply: reply } : prev);
      setGenerating(false);
      notify('AI 回复已生成');
    }, 850);
  }

  return <MotionDiv className="card demo-shell" variants={fadeUp} initial="hidden" animate="show"><aside className="demo-side" aria-label="Demo 功能导航"><b style={{ display: 'block', padding: '10px 10px 24px', fontSize: 18, letterSpacing: '-.04em' }}>Algo<span style={{ color: 'var(--brand)' }}>Lab</span></b>{nav.map(([id, label, Icon]) => <button key={id} onClick={() => setView(id)} aria-current={view === id ? 'page' : undefined} style={{ width: '100%', textAlign: 'left', border: 0, borderRadius: 12, padding: '12px 11px', marginBottom: 6, color: view === id ? 'var(--brand)' : 'var(--muted)', background: view === id ? 'var(--soft)' : 'transparent', fontWeight: view === id ? 800 : 600 }}><Icon size={16} style={{ verticalAlign: '-3px', marginRight: 9 }} />{label}</button>)}</aside><section className="demo-main"><div className="demo-help"><span>① 切换模型视图</span><span>② 点击会话打开识别详情</span><span>③ 点击“生成 AI 回复”体验推理反馈</span></div>{toast && <Toast>{toast}</Toast>}{view === 'overview' && <Overview metrics={metrics} range={range} setRange={setRange} />}{view === 'knowledge' && <Knowledge items={items} add={(item) => { setItems([item, ...items]); notify('知识条目已保存为草稿'); }} publish={(id) => { setItems(items.map((item) => item.id === id ? { ...item, status: '已发布', updated: '刚刚' } : item)); notify('条目已发布，可被模型引用'); }} />}{view === 'conversations' && <Conversations items={filteredConversations} query={query} setQuery={setQuery} status={status} setStatus={setStatus} open={setSelected} />}{view === 'workflow' && <WorkflowView tab={tab} switchTab={switchTab} loading={loading} threshold={threshold} setThreshold={setThreshold} save={() => notify('模型策略已保存')} />}{selected && <ConversationDrawer item={selected} close={() => setSelected(null)} markHandled={markHandled} generateReply={generateReply} generating={generating} />}</section></MotionDiv>;
}

function Overview({ metrics, range, setRange }: { metrics: { resolution: number; satisfaction: number; tickets: number; trend: number[] }; range: string; setRange: (range: '7d' | '30d') => void }) { return <MotionDiv variants={fadeUp} initial="hidden" animate="show"><Header title="模型概览" sub="意图识别效果、满意度代理指标与样本量" extra={<Segmented range={range} setRange={setRange} />} /><div className="grid metric-grid">{[['Macro F1', `${metrics.resolution / 100}`, '+0.18'], ['AUC', `${metrics.satisfaction / 100}`, '+0.06'], ['样本会话', metrics.tickets.toLocaleString(), 'mock dataset']].map(([label, value, delta]) => <MotionDiv whileHover={{ y: -4 }} className="card glass" style={{ padding: 18 }} key={label}><p className="muted" style={{ margin: 0, fontSize: 13 }}>{label}</p><b style={{ fontSize: 30, letterSpacing: '-.05em' }}>{value}</b><p style={{ margin: '6px 0 0', color: 'var(--success)', fontSize: 12, fontWeight: 800 }}>{delta}</p></MotionDiv>)}</div><div className="card" style={{ marginTop: 20, padding: 22 }}><b>模型指标趋势</b><p className="muted" style={{ fontSize: 13 }}>切换 7 日 / 30 日，模拟观察模型迭代后的指标变化。</p><div style={{ display: 'flex', height: 210, alignItems: 'end', gap: 8, marginTop: 22 }}>{metrics.trend.map((value, index) => <MotionDiv key={`${range}-${index}`} initial={{ height: 0 }} animate={{ height: `${value}%` }} transition={{ duration: 0.45, delay: index * 0.035 }} style={{ flex: 1, background: 'linear-gradient(#635bff,#a29cff)', borderRadius: '8px 8px 0 0', minHeight: 18 }} title={`${value}%`} />)}</div></div></MotionDiv>; }
function Segmented({ range, setRange }: { range: string; setRange: (range: '7d' | '30d') => void }) { return <div style={{ display: 'flex', gap: 6, background: 'var(--soft)', padding: 4, borderRadius: 999 }}>{(['7d', '30d'] as const).map((item) => <button key={item} className={range === item ? 'btn btn-primary' : 'btn'} onClick={() => setRange(item)} style={{ padding: '7px 12px', background: range === item ? undefined : 'transparent', color: range === item ? undefined : 'var(--muted)' }}>{item === '7d' ? '7 日' : '30 日'}</button>)}</div>; }
function Knowledge({ items, add, publish }: { items: KnowledgeItem[]; add: (item: KnowledgeItem) => void; publish: (id: number) => void }) { const [title, setTitle] = useState(''); const [category, setCategory] = useState('算法知识'); const [error, setError] = useState(''); function submit() { if (title.trim().length < 4) { setError('标题至少 4 个字，方便模型检索。'); return; } add({ id: Date.now(), title: title.trim(), category, status: '草稿', updated: '刚刚' }); setTitle(''); setError(''); } return <MotionDiv variants={fadeUp} initial="hidden" animate="show"><Header title="知识库" sub="维护模型可引用的验证知识；新增后可发布" extra={null} /><div className="card glass knowledge-form"><div><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="例如：低置信度意图如何处理？" style={{ width: '100%', border: '1px solid var(--line)', borderRadius: 12, padding: '11px', background: 'var(--paper)', color: 'var(--ink)' }} />{error && <div className="field-error">{error}</div>}</div><select value={category} onChange={(event) => setCategory(event.target.value)} style={{ border: '1px solid var(--line)', borderRadius: 12, background: 'var(--paper)', color: 'var(--ink)', padding: '0 12px' }}><option>算法知识</option><option>账单与订阅</option><option>账户管理</option></select><button className="btn btn-primary" onClick={submit} style={{ padding: '10px 14px' }}><Plus size={16} />新增条目</button></div><div style={{ marginTop: 16 }}>{items.map((item) => <MotionDiv layout key={item.id} className="card interactive-row" style={{ padding: 16, marginBottom: 10, display: 'flex', justifyContent: 'space-between', gap: 12, boxShadow: 'none' }}><div><b>{item.title}</b><p className="muted" style={{ margin: '5px 0 0', fontSize: 13 }}>{item.category} · {item.updated}</p></div><div style={{ display: 'flex', gap: 8, alignItems: 'center' }}><StatusPill status={item.status} />{item.status === '草稿' && <button className="btn btn-secondary" onClick={() => publish(item.id)} style={{ padding: '7px 10px', fontSize: 12 }}>发布</button>}</div></MotionDiv>)}</div></MotionDiv>; }
function Conversations({ items, query, setQuery, status, setStatus, open }: { items: Conversation[]; query: string; setQuery: (query: string) => void; status: string; setStatus: (status: string) => void; open: (item: Conversation) => void }) { return <MotionDiv variants={fadeUp} initial="hidden" animate="show"><Header title="会话意图识别" sub="点击任意会话查看模型置信度、AI 回复生成与人工接管建议" extra={null} /><div style={{ display: 'flex', gap: 10, marginBottom: 16, flexWrap: 'wrap' }}><div style={{ position: 'relative', flex: '1 1 260px' }}><Search size={15} style={{ position: 'absolute', left: 12, top: 13, color: 'var(--muted)' }} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索客户、主题或渠道" style={{ width: '100%', padding: '11px 11px 11px 34px', border: '1px solid var(--line)', borderRadius: 12, background: 'var(--paper)', color: 'var(--ink)' }} /></div><select value={status} onChange={(event) => setStatus(event.target.value)} style={{ border: '1px solid var(--line)', borderRadius: 12, background: 'var(--paper)', color: 'var(--ink)', padding: '0 12px' }}><option>全部</option><option>已解决</option><option>需跟进</option></select></div>{items.map((item) => <MotionDiv layout role="button" tabIndex={0} onClick={() => open(item)} onKeyDown={(event) => event.key === 'Enter' && open(item)} key={item.id} className="card interactive-row conversation-row"><div><b>{item.customer}</b><span className="muted" style={{ fontSize: 12 }}> · {item.topic} · {item.channel}</span><p className="muted" style={{ fontSize: 12, margin: '5px 0 0' }}>{item.id} · {item.time} · 点击生成/查看 AI 回复</p></div><span style={{ fontSize: 12, color: item.confidence < 70 ? 'var(--warning)' : 'var(--success)', fontWeight: 800 }}>置信度 {item.confidence}%</span><StatusPill status={item.status} /></MotionDiv>)}{!items.length && <div className="empty-state">没有符合条件的会话。试试清空关键词或切换状态。</div>}</MotionDiv>; }
function ConversationDrawer({ item, close, markHandled, generateReply, generating }: { item: Conversation; close: () => void; markHandled: (id: string) => void; generateReply: (item: Conversation) => void; generating: boolean }) { const risky = item.confidence < 70; return <div className="drawer-backdrop" onClick={close}><MotionDiv className="drawer" initial={{ x: 80, opacity: 0 }} animate={{ x: 0, opacity: 1 }} onClick={(event) => event.stopPropagation()}><button aria-label="关闭详情" onClick={close} style={{ float: 'right', border: 0, background: 'transparent', color: 'var(--muted)' }}><X size={20} /></button><p className="eyebrow">INTENT DETAIL</p><h2 style={{ letterSpacing: '-.05em' }}>{item.customer}</h2><p className="muted">{item.id} · {item.channel} · {item.time}</p><div className="card glass" style={{ padding: 16, margin: '18px 0' }}><b>{item.topic}</b><p className="muted" style={{ lineHeight: 1.7 }}>模型预测意图：{item.topic}。当前置信度为 {item.confidence}%。</p></div>{risky && <div style={{ border: '1px solid #fed7aa', color: 'var(--warning)', borderRadius: 14, padding: 14, marginBottom: 14 }}><AlertTriangle size={16} style={{ verticalAlign: '-3px', marginRight: 7 }} />建议人工接管：置信度低于策略阈值。</div>}<h3>AI 生成回复</h3><div className="card" style={{ padding: 16, boxShadow: 'none', minHeight: 110 }}><p className="muted" style={{ lineHeight: 1.8 }}>{generating ? '模型推理中：正在检索知识库、判断意图边界并生成回复……' : item.aiReply || '尚未生成。点击下方按钮模拟 AI 回复生成。'}</p></div>{item.note && <p style={{ color: 'var(--success)', fontWeight: 800 }}><UserCheck size={16} style={{ verticalAlign: '-3px', marginRight: 6 }} />{item.note}</p>}<div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', marginTop: 16 }}><button className="btn btn-primary" onClick={() => generateReply(item)} disabled={generating}><Sparkles size={16} />{generating ? '生成中...' : '生成 AI 回复'}</button><button className="btn btn-secondary" onClick={() => markHandled(item.id)}><UserCheck size={16} />标记人工处理完成</button></div></MotionDiv></div>; }
function WorkflowView({ tab, switchTab, loading, threshold, setThreshold, save }: { tab: string; switchTab: (tab: string) => void; loading: boolean; threshold: number; setThreshold: (value: number) => void; save: () => void }) { return <MotionDiv variants={fadeUp} initial="hidden" animate="show"><Header title="模型策略" sub="配置意图识别、回复策略与低置信度兜底" extra={null} /><div style={{ borderBottom: '1px solid var(--line)', display: 'flex', gap: 22, overflowX: 'auto' }}>{['意图识别', '回复策略', '人工转接'].map((item) => <button key={item} onClick={() => switchTab(item)} style={{ padding: '11px 0', border: 0, borderBottom: tab === item ? '2px solid var(--brand)' : '2px solid transparent', background: 'transparent', color: tab === item ? 'var(--brand)' : 'var(--muted)', fontWeight: 800, whiteSpace: 'nowrap' }}>{item}</button>)}</div>{loading ? <MotionDiv className="card" initial={{ opacity: 0.35 }} animate={{ opacity: 0.62 }} style={{ height: 190, marginTop: 20, background: 'linear-gradient(90deg,var(--paper),var(--soft),var(--paper))' }} /> : <MotionDiv className="card glass" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} style={{ padding: 22, marginTop: 20 }}><h3 style={{ marginTop: 0 }}>{tab}</h3>{tab === '人工转接' ? <><p className="muted">当模型置信度低于阈值时，自动进入人工复核，避免低置信度误答。</p><label>置信度阈值：<b>{threshold}%</b></label><input type="range" min="40" max="95" value={threshold} onChange={(event) => setThreshold(Number(event.target.value))} style={{ width: '100%', margin: '18px 0' }} /><p className="muted" style={{ fontSize: 13 }}>当前策略：低于 {threshold}% 的会话进入“需跟进”队列。</p></> : <p className="muted">{tab === '意图识别' ? '当前启用 18 个核心意图，并将未知问题归入待标注队列。' : '基于已发布知识库生成回复；敏感或未覆盖内容将引导人工处理。'}</p>}<button className="btn btn-primary" onClick={save}><Save size={15} />保存配置</button></MotionDiv>}</MotionDiv>; }
function Toast({ children }: { children: ReactNode }) { return <MotionDiv initial={{ opacity: 0, y: 18, scale: 0.96 }} animate={{ opacity: 1, y: 0, scale: 1 }} style={{ position: 'fixed', right: 24, bottom: 24, background: '#087a51', color: 'white', padding: '12px 15px', borderRadius: 12, zIndex: 60, boxShadow: '0 18px 40px rgba(8,122,81,.3)' }}><CheckCircle2 size={16} style={{ verticalAlign: '-3px', marginRight: 7 }} />{children}</MotionDiv>; }
function StatusPill({ status }: { status: string }) { const positive = status === '已发布' || status === '已解决'; return <span style={{ height: 'fit-content', fontSize: 12, padding: '5px 9px', borderRadius: 999, background: positive ? '#d5f5e8' : 'var(--soft)', color: positive ? '#087a51' : 'var(--brand)', fontWeight: 800, whiteSpace: 'nowrap' }}>{status}</span>; }
function Header({ title, sub, extra }: { title: string; sub: string; extra: ReactNode }) { return <div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, alignItems: 'start', marginBottom: 24, flexWrap: 'wrap' }}><div><h2 style={{ fontSize: 26, margin: 0, letterSpacing: '-.04em' }}>{title}</h2><p className="muted" style={{ margin: '6px 0 0', fontSize: 13 }}>{sub}</p></div>{extra}</div>; }
